Task 1
sergey-berezin/s02170669 pull request #1
Opened 2020-09-23 16:52 UTC by VladPyatov

Здравствуйте. Получилось три варианта:
**Standard** - вся логика инкапсулирована в классе Model. Реализация параллельной работы:
Файлы "поступают" в массив Images с помощью Directory.GetFiles. Заводится счётчик обработанных файлов (инициализируется -1). Для каждого потока методом Interlocked.Increment извлекается увеличенное значение индекса массива Images и производится расчет.

**EnumFiles** - отличается от Standard только способом загрузки изображений. Команда Directory.EnumerateFiles (как и ожидается) срабатывает в 5 раз быстрее. Но если к тому моменту как потоки начнут работу еще ни одно изображение не загрузилось, потоки свою работу завершат! Во время тестирования подобного не наблюдалось. Скорее всего из-за высокой скорости чтения с SSD накопителя... Доказательств того, что Directory.EnumerateFiles постоянно считывает необходимое потокам количество файлов у меня нет:( Интересны ваши мысли по этому поводу. Для параллельной работы извлекается IEnumerator, который в потоке блокируется командой lock, позволяя тем самым извлечь "следующий" путь изображения.

**OneClassOneJob** - ваше предложение. Класс Model отвечает только за расчет для входного изображения. Для параллельной работы используется класс Parallelizer, файлы поступают в ConcurrentQueue. Но есть ли смысл так урезать функциональность Model...

2020-10-05 08:06 UTC, sergey-berezin requested changes
Пожалуйста удалите .vs из PR.

2020-10-05 11:50 UTC, VladPyatov commented
Удалено

2020-10-12 08:54 UTC, sergey-berezin requested changes

2020-10-12 08:54 UTC, sergey-berezin commented on Task_1/RecognitionModel/Parallelizer.cs
> +            Console.CancelKeyPress += new ConsoleCancelEventHandler((s, args)=>{args.Cancel = true; cts.Cancel();});
Неявное изменение реакции на Ctrl+C при использовании библиотеки.

2020-10-12 09:09 UTC, sergey-berezin approved these changes

2020-10-12 09:09 UTC, merged